package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"posts-service/internal/handler/graphql/dataloader"
	"posts-service/internal/handler/graphql/generated"
	"posts-service/internal/handler/graphql/graphmodel"
	"posts-service/internal/model"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, first *int32, after *string) (*graphmodel.CommentConnection, error) {
	page, err := model.NewPage(first, after)
	if err != nil {
		return nil, err
	}

	if page.After == nil {
		if loaders := dataloader.For(ctx); loaders != nil {
			result, err := loaders.LoadReplies(ctx, obj.ID, page.Limit)
			if err != nil {
				return nil, err
			}
			return commentConnection(result.Items, result.HasNext), nil
		}
	}

	items, hasNext, err := r.comments.ListReplies(ctx, obj.ID, page)
	if err != nil {
		return nil, err
	}
	return commentConnection(items, hasNext), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input graphmodel.CreatePostInput) (*model.Post, error) {
	return r.posts.CreatePost(ctx, input.Title, input.Content, input.Author, input.CommentsDisabled)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input graphmodel.CreateCommentInput) (*model.Comment, error) {
	return r.comments.CreateComment(ctx, input.PostID, input.ParentID, input.Author, input.Text)
}

// SetCommentsDisabled is the resolver for the setCommentsDisabled field.
func (r *mutationResolver) SetCommentsDisabled(ctx context.Context, postID string, author string, disabled bool) (*model.Post, error) {
	return r.posts.SetCommentsDisabled(ctx, postID, author, disabled)
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first *int32, after *string) (*graphmodel.CommentConnection, error) {
	page, err := model.NewPage(first, after)
	if err != nil {
		return nil, err
	}
	items, hasNext, err := r.comments.ListTopLevel(ctx, obj.ID, page)
	if err != nil {
		return nil, err
	}
	return commentConnection(items, hasNext), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int32, after *string) (*graphmodel.PostConnection, error) {
	page, err := model.NewPage(first, after)
	if err != nil {
		return nil, err
	}
	items, hasNext, err := r.posts.ListPosts(ctx, page)
	if err != nil {
		return nil, err
	}
	return postConnection(items, hasNext), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	return r.posts.GetPost(ctx, id)
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	if _, err := r.posts.GetPost(ctx, postID); err != nil {
		return nil, err
	}
	return r.bus.Subscribe(ctx, postID), nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	commentResolver      struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	postResolver         struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
