// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphmodel

import (
	"posts-service/internal/model"
)

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string         `json:"cursor"`
	Node   *model.Comment `json:"node"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Author   string  `json:"author"`
	Text     string  `json:"text"`
}

type CreatePostInput struct {
	Title            string `json:"title"`
	Content          string `json:"content"`
	Author           string `json:"author"`
	CommentsDisabled bool   `json:"commentsDisabled"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Cursor string      `json:"cursor"`
	Node   *model.Post `json:"node"`
}

type Query struct {
}

type Subscription struct {
}
